### ISSUE TITLE
Cannot use docblockr on PHP

### ISSUE THREAD

**Issue by bmanth60** [jeremyvii/vs-docblockr#11]
**Describe the bug**
I am getting the error:
```
ERR Cannot read property 'col' of null: TypeError: Cannot read property 'col' of null
	at PHP.tokenize (/home/b/.vscode-oss/extensions/jeremyljackson.vs-docblock-0.4.0/out/src/languages/php.js:129:22)
	at PHP.tokenize (/home/b/.vscode-oss/extensions/jeremyljackson.vs-docblock-0.4.0/out/src/languages/php.js:135:26)
	at PHP.tokenize (/home/b/.vscode-oss/extensions/jeremyljackson.vs-docblock-0.4.0/out/src/languages/php.js:135:26)
	at PHP.init (/home/b/.vscode-oss/extensions/jeremyljackson.vs-docblock-0.4.0/out/src/parser.js:71:28)
	at Snippets.provideCompletionItems (/home/b/.vscode-oss/extensions/jeremyljackson.vs-docblock-0.4.0/out/src/snippets.js:52:42)
	at /usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:755:678
	at /usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:108:431)
	at e.provideCompletionItems (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:755:632)
	at /usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:767:852
	at e._withAdapter (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:761:91)
	at e.$provideCompletionItems (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:767:814)
	at e._doInvokeHandler (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**To Reproduce**
1. Go to a php file
2. Enter `/**`

**Expected behavior**
Docblockr to insert the doc block template

**Enviroment (please complete the following information):**
![screenshot_2018-11-20_12-51-25](https://user-images.githubusercontent.com/5578150/48802119-15018880-ecc3-11e8-95aa-0bd39479c05c.png)

**Comment by jeremyvii** [comment]
Could you send me a snippet of the code you are trying to apply the doc block too?

**Comment by bmanth60** [comment]
sure!
```php
public function generateAdSlotName(int $id, string $device, ?string $special, ?string $position): string
{
   return "";
}
```

**Comment by jeremyvii** [comment]
Thanks! This should be fixed when the extension in your editor is updated to [0.4.2](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.4.2). Feel free to reopen this if this does not resolve the issue on your end.
